# Generated by Django 2.1.2 on 2018-12-02 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_project', '0001_initial'),
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposition',
            name='related_skills',
            field=models.ManyToManyField(to='user_profile.Skills'),
        ),
        migrations.AddField(
            model_name='projectapplicant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_project.Project'),
        ),
        migrations.AddField(
            model_name='projectapplicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
