# Generated by Django 2.2a1 on 2019-02-09 23:41

from django.core.management import call_command
from django.db import migrations

fixture = 'initial_data'


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='create_project')


class Migration(migrations.Migration):
    dependencies = [
        ('create_project', '0001_initial'),
        ('user_profile', '0002_auto_20190209_2323'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
