# Generated by Django 2.2a1 on 2019-03-03 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
        ('create_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposition',
            name='related_skills',
            field=models.ManyToManyField(to='user_profile.Skill'),
        ),
        migrations.AddField(
            model_name='projectapplicant',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_project.ProjectPosition'),
        ),
        migrations.AddField(
            model_name='projectapplicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
