# Generated by Django 2.2a1 on 2019-03-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_project', '0002_auto_20190303_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposition',
            name='related_skills',
            field=models.ManyToManyField(blank=True, to='user_profile.Skill'),
        ),
    ]
