# Generated by Django 2.2a1 on 2019-02-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_project', '0003_auto_20190213_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplicant',
            name='status',
            field=models.CharField(choices=[('a', 'Accepted'), ('r', 'Rejected'), ('p', 'Pending')], default='p', max_length=10),
        ),
    ]
