# Generated by Django 2.1.2 on 2018-12-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_project', '0003_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='timeline',
        ),
        migrations.AddField(
            model_name='project',
            name='time_involvement',
            field=models.IntegerField(default=60),
        ),
    ]
