# Generated by Django 2.2a1 on 2019-02-09 23:23

from django.core.management import call_command
from django.db import migrations

fixture = 'initial_data'


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='user_profile')


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
