# Generated by Django 2.2a1 on 2019-02-14 01:19

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190209_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
